# Generated by Django 3.2.5 on 2021-11-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=150)),
                ('action_name', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=150)),
            ],
        ),
    ]
